parameters:
- name: jobName
  default:
- name: environmentToRun
  default:
- name: versionToRun
  default:
- name: isMultiSuiteExecution
  default: false
- name: azureTimeout
  default: 60

jobs:
- job: Running_${{ parameters.jobName }}
  displayName: Running - '${{ parameters.jobName }}'
  timeoutInMinutes: ${{ parameters.azureTimeout }}

  pool:
    vmImage: windows-2022
  
  steps:
  - template: installation-steps.yml
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        if [ "${{ parameters.testSubTagName }}" == "<default>" ]; then
          if [ "${{ parameters.environmentToRun }}" == "production" ]; then
            echo "production"
            echo "##vso[task.setvariable variable=testsubtag]PROD"
          elif [ "${{ parameters.environmentToRun }}" == "sandbox" ]; then
            echo "sandbox"
            echo "##vso[task.setvariable variable=testsubtag]"
          fi
        else
          echo "##vso[task.setvariable variable=testsubtag]${{ parameters.testSubTagName }}"
        fi
        echo "Environment: ${{ parameters.environmentToRun }}"
        echo "Test Main Tag Name: ${{ parameters.testMainTagName }}"
        echo "Test Version Tag Name: ${{ parameters.versionToRun }}"
        echo "Test Sub Tag Name:" $(testsubtag)

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Environment: ${{ parameters.environmentToRun }}"
        echo "Test Main Tag Name: ${{ parameters.testMainTagName }}"
        echo "Test Version Tag Name: ${{ parameters.versionToRun }}"
        echo "Test Sub Tag Name:" $(testsubtag)

  - task: BatchScript@1
    inputs:
      filename: 'DCBankAutomation/ScriptAndYmlFiles/ScriptFiles/run.bat'
      arguments: ${{ parameters.environmentToRun }} ${{ parameters.versionToRun }} ${{ parameters.testMainTagName }} $(testSubTag)
      modifyEnvironment: false
    continueOnError: true

  - template: publish-artifact.yml
    parameters:
      jobName: ${{ parameters.jobName }}
      isMultiSuiteExecution: ${{ parameters.isMultiSuiteExecution }}
